#!/usr/bin/env python3
# GENERATED by scripts/generate_jobs.py — do not edit by hand.
"""test01 — Upper-bound baseline: one machine, all training data pooled.

NOT AN NVFLARE JOB. This is the centralised baseline: one machine, all the training
data, no server and no clients. It keeps a folder for symmetry, and because its
README belongs beside the other eight.

Run it with:
    python src/scripts/run_centralized.py
"""

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
PROJECT_ROOT = REPO_ROOT / "src" / "federated"

if __name__ == "__main__":
    sys.exit(subprocess.call(
        [sys.executable, str(REPO_ROOT / "src" / "scripts" / "run_centralized.py"),
         *sys.argv[1:]]))
