#!/usr/bin/env python3
"""Write `jobs/<experiment>/job.py` and `jobs/<experiment>/README.md` from the table.

    python scripts/generate_jobs.py
    python scripts/generate_jobs.py --check      # fail if anything is stale

GENERATED, NOT WRITTEN
----------------------
Nine job folders differing along three axes is exactly the shape of thing that
drifts. Generating them from `config/experiments.py` means a change to the protocol
cannot leave a stale README behind saying the old number of rounds, and cannot leave
job 7 using a hyperparameter job 6 stopped using.

`--check` is the guard: it regenerates into memory and compares, so a job file edited
by hand is detected rather than silently kept. Run it before submitting.

WHAT A job.py IS ALLOWED TO CONTAIN
-----------------------------------
Its own experiment id, and nothing else. No hyperparameters, no model definition, no
partition geometry. If a job file contained any of those, the nine would begin
disagreeing on day one — which is precisely how this project once ended up with a
server building a ResNet-18 while its clients built a ResNet-50.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent / "federated"
sys.path.insert(0, str(PROJECT_ROOT))

from config import experiments as EX  # noqa: E402

BANNER = "# GENERATED by scripts/generate_jobs.py — do not edit by hand."


def job_py(experiment) -> str:
    if experiment.kind == "centralized":
        return f'''#!/usr/bin/env python3
{BANNER}
"""{experiment.id} — {experiment.objective}

NOT AN NVFLARE JOB. This is the centralised baseline: one machine, all the training
data, no server and no clients. It keeps a folder for symmetry, and because its
README belongs beside the other eight.

Run it with:
    python src/scripts/run_centralized.py
"""

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
PROJECT_ROOT = REPO_ROOT / "src" / "federated"

if __name__ == "__main__":
    sys.exit(subprocess.call(
        [sys.executable, str(REPO_ROOT / "src" / "scripts" / "run_centralized.py"),
         *sys.argv[1:]]))
'''

    return f'''#!/usr/bin/env python3
{BANNER}
"""{experiment.id} — {experiment.objective}

{experiment.research_question}

Configuration only. Every hyperparameter comes from config/experiments.py and the
recipe is built by federation/recipes.py, so this file cannot disagree with the
other eight.

Run it with:
    python scripts/run_experiment.py {experiment.id}
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
PROJECT_ROOT = REPO_ROOT / "src" / "federated"
sys.path.insert(0, str(PROJECT_ROOT))

from config import experiments as EX
from federation import recipes

EXPERIMENT = EX.get("{experiment.id}")


def build():
    """The NVFLARE recipe for this experiment."""
    return recipes.build_recipe(EXPERIMENT)


def main() -> None:
    print(recipes.describe(EXPERIMENT))
    recipe = build()
    env = recipes.build_env(EXPERIMENT.n_clients)
    run = recipe.execute(env)
    print(f"submitted as {{run.get_job_id()}}")
    run.get_result(timeout=0.0, clean_up=False)
    print(f"status: {{run.get_status()}}")


if __name__ == "__main__":
    main()
'''


ALGORITHM_NOTES = {
    "fedavg":
        "**FedAvg** (McMahan et al., 2017) — the server averages the client updates, "
        "weighting each by how much data that site trained on. The baseline "
        "aggregation, and the reference every other one is measured against.",
    "fedprox":
        "**FedProx** (Li et al., 2020) — identical aggregation to FedAvg. The whole "
        "difference is on the CLIENT, which adds `mu/2 * ||w - w_global||^2` to its "
        "local loss so a site cannot drift far from the model it was given. It exists "
        "to stabilise training when the sites hold different data. A client that "
        "receives `mu` and ignores it is running FedAvg while this file claims "
        "otherwise, so `federation/recipes.py` refuses to build a FedProx job with "
        "`mu <= 0`.",
    "fedopt":
        "**FedOpt** (Reddi et al., 2021) — the mirror image of FedProx: the CLIENT is "
        "an ordinary FedAvg client (`mu = 0`) and the whole difference is on the "
        "SERVER. Instead of adopting the weighted mean of the client models, the "
        "server treats that mean as a pseudo-gradient and takes an optimiser step "
        "with it:\n\n"
        "    delta    = mean(w_client - w_global)\n"
        "    w_global = ServerOpt(w_global, delta)\n\n"
        "SGD with `lr = 1.0` and `momentum = 0` reproduces FedAvg exactly, so the "
        "server momentum is the entire difference. Being server-side, FedOpt is "
        "ORTHOGONAL to FedProx rather than an alternative — the two could be "
        "combined, and are not here.",
}


def split_table(experiment) -> str:
    if experiment.partition is None:
        return ("All training patients on one machine — this is the pooled baseline, "
                "not a split.\n")
    partition = EX.PARTITIONS[experiment.partition]
    rows = "\n".join(
        f"| `{name}` | {100 * frac:.1f}% | {ratio:g} |"
        for name, frac, ratio in zip(partition.client_names, partition.fractions,
                                     partition.ratio))
    stratified = (
        "The split is **stratified**: every hospital keeps the global class ratio, so "
        "the only thing that varies between them is QUANTITY. This is a deliberate "
        "limitation and the dissertation states it — tests 08 and 09 are quantity "
        "skew, not genuine non-IID heterogeneity."
        if partition.stratified else
        "The split is **not stratified**: hospitals differ in label distribution as "
        "well as in size.")
    return f"""Patients are divided **by patient, never by slice**: every image of a
patient goes to exactly one hospital, and no patient appears at two sites. Splitting
by slice would let a model recognise the patient rather than the disease.

| hospital | share of training patients | ratio |
|---|---:|---:|
{rows}

{stratified}

Each hospital additionally holds out {100 * EX.FEDERATION.local_val_fraction:.0f}% of
its own patients as a local validation split. That is what produces the metric the
server selects on, and it is local by construction: a hospital cannot validate on
another hospital's patients.

Data lives in `data/partitions/{partition.name}/<hospital>/`, written by
`scripts/partition_data.py` and checked by `scripts/verify_data.py`.
"""


def job_readme(experiment) -> str:
    fed, tr = EX.FEDERATION, EX.TRAINING

    if experiment.kind == "federated":
        mu = fed.fedprox_mu if experiment.algorithm == "fedprox" else 0.0
        command = f"python scripts/run_experiment.py {experiment.id}"
        algorithm = (f"## Aggregation algorithm\n\n"
                     f"{ALGORITHM_NOTES[experiment.algorithm]}\n")
        protocol = [
            ("rounds x local epochs", f"{fed.num_rounds} x {fed.local_epochs}"),
            ("total epochs of data", f"{fed.num_rounds * fed.local_epochs} "
                                     f"(budget-matched to the centralised baseline)"),
            ("model selection", f"`{fed.key_metric}`, on held-out client patients — "
                                f"never training accuracy"),
        ]
        if experiment.algorithm == "fedprox":
            protocol.append(("FedProx mu", f"{mu}"))
        if experiment.algorithm == "fedopt":
            protocol.append(("server optimiser",
                             f"SGD, lr {fed.fedopt_lr}, momentum "
                             f"{fed.fedopt_momentum}, on CPU"))
            protocol.append(("client mu", "0 — an ordinary FedAvg client"))
    else:
        command = "python src/scripts/run_centralized.py"
        algorithm = ("## Aggregation algorithm\n\nNone — there is no server and there "
                     "are no clients. This is the upper bound the federated runs are "
                     "measured against.\n")
        protocol = [
            ("epochs", f"{fed.centralized_epochs} (budget-matched to "
                       f"{fed.num_rounds} rounds x {fed.local_epochs})"),
            ("model selection", f"validation `{tr.monitor_metric}`"),
        ]

    protocol += [
        ("model", f"`{tr.model_name}`, ImageNet-pretrained, {EX.NUM_CLASSES} classes"),
        ("frozen", f"`{tr.freeze_until}` — conv1+bn1+layer1+layer2 "
                   f"(the configuration whose seed spread was 0.003, not 0.026)"),
        ("input", f"{tr.image_size}x{tr.image_size} RGB, three DCE phases fused"),
        ("optimiser", f"{tr.optimizer}, lr {tr.learning_rate}, "
                      f"weight decay {tr.weight_decay}"),
        ("regularisation", f"dropout {tr.dropout}, label smoothing "
                           f"{tr.label_smoothing}, gradient clip 1.0"),
        ("batch size", f"{tr.batch_size}, at most "
                       f"{tr.max_slices_per_patient_per_batch} slice per patient"),
        ("class weights", f"inverse frequency per PATIENT, scope "
                          f"`{tr.class_weight_scope}`"),
        ("seed", f"{tr.seed}"),
    ]
    protocol_rows = "\n".join(f"| {k} | {v} |" for k, v in protocol)
    notes = f"\n## Notes\n\n{experiment.notes}\n" if experiment.notes else ""

    return f"""<!-- {BANNER[2:]} -->
# {experiment.id} — {experiment.name}

## Objective

{experiment.objective}

## Research question

{experiment.research_question}

## Hospitals

**{experiment.n_clients}** — {experiment.split_label}

## Data split

{split_table(experiment)}
{algorithm}
## Protocol

| | |
|---|---|
{protocol_rows}

Every value above comes from `config/experiments.py`. Nothing is set in this folder.

## Run

```bash
{command}
```

## What this produces

`results/{experiment.name}/` — the model, `rounds.csv` (one row per round per
hospital), per-patient predictions on the global test set, the resolved
configuration, and the full log. Enough to regenerate every dissertation figure
without re-running anything.
{notes}
## Evaluation

Reported at **patient level**: slice probabilities are averaged into one prediction
per patient before any metric, because slices of one patient are near-duplicates and
a slice-level score measures patient recognition rather than disease. The headline
metric is one-vs-rest **macro-AUC**. Accuracy is never quoted without the trivial
baseline of the same split beside it.

All nine experiments are scored on the **same global test set**, which no hospital
sees during training.

## Reading the result

The noise floor on this task is **0.067 macro-AUC**, measured between two runs of a
byte-identical configuration differing only in random seed. Treat a smaller
difference as "no difference detected" — that is a finding, and belongs in the
dissertation as one. One seed is not a result.
"""


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--check", action="store_true",
                   help="exit non-zero if any generated file is stale")
    args = p.parse_args()

    stale: list[str] = []
    for experiment in EX.EXPERIMENTS:
        job_dir = EX.JOBS_DIR / experiment.name
        for filename, content in (("job.py", job_py(experiment)),
                                  ("README.md", job_readme(experiment))):
            path = job_dir / filename
            current = path.read_text() if path.is_file() else None
            if current == content:
                continue
            if args.check:
                stale.append(str(path.relative_to(EX.REPO_ROOT)))
                continue
            job_dir.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            if filename == "job.py":
                path.chmod(0o755)
            print(f"  wrote {path.relative_to(EX.REPO_ROOT)}")

    if args.check:
        if stale:
            print("STALE — regenerate with: python scripts/generate_jobs.py")
            for s in stale:
                print(f"  {s}")
            sys.exit(1)
        print(f"all {len(EX.EXPERIMENTS)} job folders are up to date")
        return
    print(f"\n{len(EX.EXPERIMENTS)} job folders generated from config/experiments.py")


if __name__ == "__main__":
    main()
