#!/usr/bin/env python3
"""Freeze the resolved configuration into `production/config/`.

    python scripts/snapshot_config.py

WHAT THIS IS, AND WHAT IT IS NOT
--------------------------------
It is a SNAPSHOT — a record of what `config/experiments.py` and
`config/federation.py` resolved to at a moment in time, written where the deployment
and its outputs live so that a results folder can be read years later without the
source tree.

It is NOT a source. Nothing reads it back. Editing it changes nothing, and the header
of every file it writes says so. That distinction is the whole reason this project
keeps one definition of each hyperparameter: three separate bugs here came from two
copies of one setting drifting apart, and a snapshot that could be read back would be
a fourth copy waiting to happen.

`verify_production.py` compares the snapshot against the live config and fails if they
disagree, so a stale snapshot is caught rather than believed.
"""

from __future__ import annotations

import json
import sys
from dataclasses import asdict
from datetime import datetime, timezone
import pathlib
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent / "federated"
sys.path.insert(0, str(PROJECT_ROOT))

from config import experiments as EX      # noqa: E402


def rel(path) -> str:
    """Repository-relative, so the snapshot stays true after a clone or a rename.

    This file records where the configuration resolved to. An absolute path
    would record where it resolved to ON ONE MACHINE, which is wrong for
    everybody else and stops being true here the moment the project folder
    moves.
    """
    path = pathlib.Path(path).resolve()
    try:
        return str(path.relative_to(EX.REPO_ROOT))
    except ValueError:
        return str(path)
from config import federation as FED      # noqa: E402

HEADER = ("GENERATED SNAPSHOT — written by scripts/snapshot_config.py. "
          "Nothing reads this back; editing it changes nothing. The source is "
          "config/experiments.py and config/federation.py.")


def payload() -> dict:
    return {
        "_comment": HEADER,
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "project": {
            "name": FED.PROJECT_NAME,
            "description": FED.PROJECT_DESCRIPTION,
            "organisation": FED.ORGANISATION,
            "source_dataset": rel(EX.SOURCE_DATASET),
            "classes": list(EX.CLASS_NAMES),
            "num_classes": EX.NUM_CLASSES,
        },
        "deployment": {
            "server": {"name": FED.SERVER_NAME, "host": FED.SERVER_HOST,
                       "fed_learn_port": FED.FED_LEARN_PORT,
                       "admin_port": FED.ADMIN_PORT},
            "admin": {"user": FED.ADMIN_USER, "role": FED.ADMIN_ROLE},
            "hospitals": [asdict(h) for h in FED.HOSPITALS],
            "workspace": rel(EX.WORKSPACE_DIR),
            "project_yml": rel(EX.PROJECT_YML),
        },
        "training": asdict(EX.TRAINING),
        "federation": asdict(EX.FEDERATION),
        "partitions": {
            name: {"n_clients": p.n_clients, "ratio": list(p.ratio),
                   "fractions": [round(f, 6) for f in p.fractions],
                   "label": p.label, "stratified": p.stratified}
            for name, p in EX.PARTITIONS.items()
        },
        "experiments": [
            {"id": e.id, "name": e.name, "kind": e.kind,
             "algorithm": e.algorithm or "centralized",
             "partition": e.partition, "n_hospitals": e.n_clients,
             "split": e.split_label, "objective": e.objective,
             "research_question": e.research_question, "notes": e.notes}
            for e in EX.EXPERIMENTS
        ],
    }


def main() -> None:
    out = EX.PRODUCTION_DIR / "config"
    out.mkdir(parents=True, exist_ok=True)
    data = payload()
    (out / "resolved_config.json").write_text(json.dumps(data, indent=2, default=str))

    tr, fed = data["training"], data["federation"]
    lines = [
        "<!-- GENERATED by scripts/snapshot_config.py — do not edit by hand. -->",
        "# Resolved configuration", "",
        f"Snapshot taken {data['generated']}. **Nothing reads this file back.** The",
        "source of every value below is `config/experiments.py` and",
        "`config/federation.py`; this is a record so that a results folder stays",
        "readable without the source tree.", "",
        "## Deployment", "",
        "| | |", "|---|---|",
        f"| server | `{FED.SERVER_NAME}` @ `{FED.SERVER_HOST}` |",
        f"| fed_learn port | `{FED.FED_LEARN_PORT}` — clients connect here |",
        f"| admin port | `{FED.ADMIN_PORT}` — job submission and monitoring |",
        f"| admin identity | `{FED.ADMIN_USER}` (`{FED.ADMIN_ROLE}`) |",
        f"| hospitals | {', '.join(f'`{h.name}`' for h in FED.HOSPITALS)} |",
        "",
        "## Model and training — identical for all nine experiments", "",
        "| | |", "|---|---|",
        f"| model | `{tr['model_name']}`, ImageNet-pretrained |",
        f"| classes | {EX.NUM_CLASSES} — {', '.join(EX.CLASS_NAMES)} |",
        f"| input | {tr['image_size']}x{tr['image_size']} RGB, 3 DCE phases fused |",
        f"| frozen | `{tr['freeze_until']}` |",
        f"| optimiser | {tr['optimizer']}, lr {tr['learning_rate']}, "
        f"weight decay {tr['weight_decay']} |",
        f"| scheduler | {tr['scheduler']} |",
        f"| regularisation | dropout {tr['dropout']}, "
        f"label smoothing {tr['label_smoothing']} |",
        f"| batch size | {tr['batch_size']}, "
        f"max {tr['max_slices_per_patient_per_batch']} slice(s) per patient |",
        f"| class weights | inverse frequency per patient, scope "
        f"`{tr['class_weight_scope']}` |",
        f"| seed | {tr['seed']} |",
        "",
        "## Federated protocol", "",
        "| | |", "|---|---|",
        f"| rounds | {fed['num_rounds']} |",
        f"| local epochs per round | {fed['local_epochs']} |",
        f"| centralised epochs | {fed['centralized_epochs']} "
        f"(budget-matched: {fed['num_rounds']} x {fed['local_epochs']}) |",
        f"| FedProx mu | {fed['fedprox_mu']} |",
        f"| server model selection | `{fed['key_metric']}` — held-out client data |",
        f"| local validation fraction | {fed['local_val_fraction']} |",
        "",
        "## The nine experiments", "",
        "| test | folder | hospitals | distribution | algorithm |",
        "|---|---|---|---|---|",
    ]
    for e in EX.EXPERIMENTS:
        algo = "—" if e.kind == "centralized" else e.algorithm
        dist = "100% pooled" if e.partition is None else e.split_label.split("->")[-1].strip()
        lines.append(f"| `{e.id}` | `{e.name}` | {e.n_clients} | {dist} | {algo} |")
    lines.append("")
    (out / "resolved_config.md").write_text("\n".join(lines))

    print(f"wrote {out / 'resolved_config.json'}")
    print(f"wrote {out / 'resolved_config.md'}")


if __name__ == "__main__":
    main()
