#!/usr/bin/env python3
# GENERATED by scripts/generate_jobs.py — do not edit by hand.
"""test05 — Same three-site split under FedProx.

RQ3 — FedAvg versus FedProx at three clients.

Configuration only. Every hyperparameter comes from config/experiments.py and the
recipe is built by federation/recipes.py, so this file cannot disagree with the
other eight.

Run it with:
    python scripts/run_experiment.py test05
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
PROJECT_ROOT = REPO_ROOT / "src" / "federated"
sys.path.insert(0, str(PROJECT_ROOT))

from config import experiments as EX
from federation import recipes

EXPERIMENT = EX.get("test05")


def build():
    """The NVFLARE recipe for this experiment."""
    return recipes.build_recipe(EXPERIMENT)


def main() -> None:
    print(recipes.describe(EXPERIMENT))
    recipe = build()
    env = recipes.build_env(EXPERIMENT.n_clients)
    run = recipe.execute(env)
    print(f"submitted as {run.get_job_id()}")
    run.get_result(timeout=0.0, clean_up=False)
    print(f"status: {run.get_status()}")


if __name__ == "__main__":
    main()
