#!/usr/bin/env python3
"""Write one complete NVFLARE job folder per federated experiment.

    python deployment/code/scripts/generate_jobs.py
    python deployment/code/scripts/generate_jobs.py --check      # fail if stale

Each folder under `deployment/jobs/` is a job the admin console can submit by name,
holding `meta.json`, the two config files, and every module the hospitals import
under `app/custom/`. Nothing in a job folder points back into this repository, so a
job can be copied to a hospital machine and submitted there.

The folders are GENERATED from `config/experiments.py`. Editing one by hand is how
this project once ran a server building a ResNet-18 against clients building a
ResNet-50, so `--check` refuses when a folder no longer matches the table.

`submit_job <name>` resolves the name against the admin's own `transfer/` directory,
not against an arbitrary path, so this script copies the folders there as well.

The centralised baseline has no job folder. It is not an NVFLARE job: one machine,
all the training data, no server and no clients. `run_centralized.py` runs it.
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import tempfile
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from config import experiments as EX
from config import federation as FED
from federation import recipes  # noqa: E402

BANNER = "# GENERATED by deployment/code/scripts/generate_jobs.py. Do not edit by hand."




ALGORITHM_SHORT = {"fedavg": "FedAvg", "fedprox": "FedProx", "fedopt": "FedOpt"}

ALGORITHM_NOTES = {
    "fedavg":
        "FedAvg (McMahan et al., 2017). The server averages the client updates, "
        "weighting each one by how much data that site trained on.",
    "fedprox":
        "FedProx (Li et al., 2020). The server aggregates exactly as FedAvg does. "
        "The difference is on the client, which adds `mu/2 * ||w - w_global||^2` to "
        "its local loss so a site cannot drift far from the model it was given.",
    "fedopt":
        "FedOpt (Reddi et al., 2021). The client is an ordinary FedAvg client "
        "(`mu = 0`). The server treats the mean client update as a pseudo-gradient "
        "and takes an optimiser step with it.",
}


def split_table(experiment) -> str:
    """The per-hospital share table, or one line saying the data is pooled."""
    if experiment.partition is None:
        return "All training patients sit on one machine. There is no split.\n"

    partition = EX.PARTITIONS[experiment.partition]
    rows = "\n".join(
        f"| `{name}` | {100 * frac:.1f}% | {ratio:g} |"
        for name, frac, ratio in zip(partition.client_names, partition.fractions,
                                     partition.ratio))
    spread = ("Every hospital keeps the global class ratio, so the hospitals differ "
              "only in how much data they hold."
              if partition.stratified else
              "Hospitals differ in label distribution as well as in size.")
    local_val = f"{100 * EX.FEDERATION.local_val_fraction:.0f}%"

    return (
        "Patients are split by patient, never by slice. Every image of a patient "
        "goes to one hospital, and no patient appears at two sites.\n"
        "\n"
        "| hospital | share of training patients | ratio |\n"
        "|---|---:|---:|\n"
        f"{rows}\n"
        "\n"
        f"{spread} Each hospital also holds back {local_val} of its own patients "
        "as a local validation split, which is what produces the metric the server "
        "selects on.\n"
        "\n"
        f"The files are in `deployment/data/partitions/{partition.name}/<hospital>/`.\n"
    )


def job_readme(experiment) -> str:
    """The README written beside each generated job folder."""
    fed, tr = EX.FEDERATION, EX.TRAINING

    protocol = [
        ("algorithm", ALGORITHM_SHORT[experiment.algorithm]),
        ("hospitals", f"{experiment.n_clients}"),
        ("partition", f"`{experiment.partition}`"),
        ("rounds x local epochs", f"{fed.num_rounds} x {fed.local_epochs}"),
        ("model selection", f"`{fed.key_metric}`, on held-out client patients"),
    ]
    if experiment.algorithm == "fedprox":
        protocol.insert(1, ("FedProx mu", f"{fed.fedprox_mu}"))
    if experiment.algorithm == "fedopt":
        protocol.insert(1, ("server optimiser",
                            f"SGD, lr {fed.fedopt_lr}, "
                            f"momentum {fed.fedopt_momentum}, on CPU"))
        protocol.insert(2, ("client mu", "0, an ordinary FedAvg client"))
    protocol += [
        ("model", f"`{tr.model_name}`, ImageNet-pretrained, {EX.NUM_CLASSES} classes"),
        ("frozen", f"`{tr.freeze_until}` and every layer before it"),
        ("input", f"{tr.image_size}x{tr.image_size} RGB, three DCE phases fused"),
        ("optimiser", f"{tr.optimizer}, lr {tr.learning_rate}, "
                      f"weight decay {tr.weight_decay}"),
        ("regularisation", f"dropout {tr.dropout}, label smoothing "
                           f"{tr.label_smoothing}, gradient clip 1.0"),
        ("batch size", f"{tr.batch_size}, at most "
                       f"{tr.max_slices_per_patient_per_batch} slice per patient"),
        ("class weights", f"inverse frequency per patient, scope "
                          f"`{tr.class_weight_scope}`"),
        ("seed", f"{tr.seed}"),
    ]
    protocol_rows = "\n".join(f"| {k} | {v} |" for k, v in protocol)

    outputs = [
        ("`global_model.pt`", "the selected global model"),
        ("`test_metrics.json`", "every metric on the global test set"),
        ("`predictions_test.csv`", "one row per test patient"),
        ("`sites/rounds.csv`", "per-round, per-site metrics"),
        ("`job.json`", "job id, timings, algorithm, client count, status"),
    ]
    output_rows = "\n".join(f"| {k} | {v} |" for k, v in outputs)

    return (
        f"<!-- {BANNER[2:]} -->\n"
        f"# {experiment.name}\n"
        "\n"
        "A complete NVFLARE job. Every module the hospitals import is inside\n"
        "`app/custom/`, so nothing is read from this repository while it runs.\n"
        "\n"
        "## What is in the folder\n"
        "\n"
        "```\n"
        f"{experiment.name}/\n"
        "├── meta.json                             name, min_clients, deploy_map\n"
        "└── app/\n"
        "    ├── config/config_fed_server.json     controller, rounds, model selector\n"
        "    ├── config/config_fed_client.json     executor and the client command line\n"
        "    └── custom/                           the code that runs at each hospital\n"
        "        ├── federation/client.py\n"
        "        ├── config/  common/  core/  pipelines/\n"
        "        └── dataset_config.py\n"
        "```\n"
        "\n"
        "## What it runs\n"
        "\n"
        "| | |\n"
        "|---|---|\n"
        f"{protocol_rows}\n"
        "\n"
        f"{ALGORITHM_NOTES[experiment.algorithm]}\n"
        "\n"
        "## Data\n"
        "\n"
        f"{split_table(experiment)}"
        "\n"
        "## How to run it\n"
        "\n"
        f"Start the federation with {experiment.n_clients} hospitals, open the admin\n"
        "console, and submit the job by name:\n"
        "\n"
        "```\n"
        f"submit_job {experiment.name}\n"
        "```\n"
        "\n"
        "`submit_job` looks names up in the admin's own `transfer/` directory.\n"
        "`generate_jobs.py` copies this folder there, so the name is enough.\n"
        "\n"
        "The scripted equivalent, which also writes `job.json` and the admin log:\n"
        "\n"
        "```bash\n"
        f"python deployment/code/scripts/run_experiment.py {experiment.id}\n"
        "```\n"
        "\n"
        "## What it writes\n"
        "\n"
        f"`results/federated/{experiment.name}/`\n"
        "\n"
        "| File | What it is |\n"
        "|---|---|\n"
        f"{output_rows}\n"
    )


def build_job_folder(experiment, dest: Path) -> None:
    """Write one complete, self-contained NVFLARE job folder.

    The result is what `submit_job` expects and nothing else:

        <name>/
          meta.json
          app/config/config_fed_server.json
          app/config/config_fed_client.json
          app/custom/...              every module the client imports

    `recipes.build_recipe` stages the code and records a relative
    `task_script_path`, so nothing in here points outside the folder.
    """
    recipe = recipes.build_recipe(experiment)
    with tempfile.TemporaryDirectory(prefix="fl_job_") as tmp:
        recipe.export(job_dir=tmp, env=recipes.build_env(experiment.n_clients))
        built = Path(tmp) / experiment.name
        if not built.is_dir():                      # nvflare names it after the recipe
            built = next(p for p in Path(tmp).iterdir() if p.is_dir())
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(built, dest)


def job_fingerprint(job_dir: Path) -> dict[str, str]:
    """Every file in a job folder and its sha256, for comparing two builds."""
    out = {}
    for f in sorted(job_dir.rglob("*")):
        if f.is_file() and f.name != "README.md" and "__pycache__" not in f.parts:
            out[str(f.relative_to(job_dir))] = hashlib.sha256(f.read_bytes()).hexdigest()
    return out


def install_for_admin(jobs_dir: Path) -> Path | None:
    """Copy the jobs into the admin's upload directory.

    `submit_job <name>` resolves the name against the admin's `upload_dir`, which
    provisioning sets to `transfer` inside the admin's own startup kit. A job that
    is not in there cannot be submitted by name, and an absolute path does not work
    because the folder is zipped relative to that directory.

    Provisioning recreates the kit, so this is a copy rather than the only home:
    `deployment/jobs/` stays the version-controlled original.
    """
    try:
        transfer = Path(FED.startup_kit(FED.ADMIN_USER)) / "transfer"
    except SystemExit:
        return None
    if not transfer.parent.is_dir():
        return None
    transfer.mkdir(parents=True, exist_ok=True)
    for job in sorted(jobs_dir.iterdir()):
        if not job.is_dir():
            continue
        dst = transfer / job.name
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(job, dst, ignore=shutil.ignore_patterns("README.md"))
    return transfer


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--check", action="store_true",
                   help="exit non-zero if any generated file is stale")
    p.add_argument("--no-install", action="store_true",
                   help="do not copy the jobs into the admin's transfer directory")
    args = p.parse_args()

    federated = [e for e in EX.EXPERIMENTS if e.kind == "federated"]
    stale: list[str] = []

    for experiment in federated:
        job_dir = EX.JOBS_DIR / experiment.name
        readme = job_dir / "README.md"

        if args.check:
            with tempfile.TemporaryDirectory(prefix="fl_check_") as tmp:
                fresh = Path(tmp) / experiment.name
                build_job_folder(experiment, fresh)
                if job_fingerprint(fresh) != job_fingerprint(job_dir):
                    stale.append(f"{job_dir.relative_to(EX.REPO_ROOT)}/")
            if (readme.read_text() if readme.is_file() else None) != job_readme(experiment):
                stale.append(str(readme.relative_to(EX.REPO_ROOT)))
            continue

        build_job_folder(experiment, job_dir)
        readme.write_text(job_readme(experiment))
        n = sum(1 for f in job_dir.rglob("*") if f.is_file())
        print(f"  {experiment.name:<28} {n:>3} files")

    if args.check:
        if stale:
            print("STALE — regenerate with: "
                  "python deployment/code/scripts/generate_jobs.py")
            for s in stale:
                print(f"  {s}")
            sys.exit(1)
        print(f"all {len(federated)} job folders are up to date")
        return

    print(f"\n{len(federated)} job folders written to "
          f"{EX.JOBS_DIR.relative_to(EX.REPO_ROOT)}/")

    if not args.no_install:
        transfer = install_for_admin(EX.JOBS_DIR)
        if transfer:
            print(f"installed for the admin console: {transfer}")
            print("submit one with:  submit_job <name>")
        else:
            print("no provisioned admin kit yet — run provision.sh, then this again")


if __name__ == "__main__":
    main()
